trigger:
- main

variables:
- group: SAG_SETTINGS
- name: PROJECT_NAME
  value: $(Build.DefinitionName)

pool:
  name: Default  # self-hosted Windows agent

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - checkout: self

    - script: |
        call "%SAG_HOME%\common\lib\ant\bin\ant" ^
          -DSAGHome=%SAG_HOME% ^
          -DSAG_CI_HOME=%SAG_CI_HOME% ^
          -DprojectName=%PROJECT_NAME% build
      displayName: 'Build with Ant'

    - publish: '$(System.DefaultWorkingDirectory)/target'
      artifact: BuildOutput
      displayName: 'Publish Build Artifacts'

- stage: Deploy
  dependsOn: Build
  jobs:
  - job: DeployJob
    steps:
    - download: current
      artifact: BuildOutput
      displayName: 'Download Build Artifacts'

    - script: |
        echo === Artifact content ===
        dir "$(Pipeline.Workspace)\BuildOutput" /s
      displayName: 'List Artifact Content (Debug)'

    - script: |
        call "%SAG_HOME%\common\lib\ant\bin\ant" ^
          -DSAGHome=%SAG_HOME% ^
          -DSAG_CI_HOME=%SAG_CI_HOME% ^
          -DprojectName=%PROJECT_NAME% ^
          -Dbuild.dir=$(Pipeline.Workspace)\BuildOutput deploy
      displayName: 'Deploy with Ant'

- stage: Test
  dependsOn: Deploy
  jobs:
  - job: TestJob
    steps:
    - script: |
        call "%SAG_HOME%\common\lib\ant\bin\ant" ^
          -DSAGHome=%SAG_HOME% ^
          -DSAG_CI_HOME=%SAG_CI_HOME% ^
          -DprojectName=%PROJECT_NAME% test
      displayName: 'Test with Ant'

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/report/*.xml'
        failTaskOnFailedTests: true
      displayName: 'Publish JUnit Test Results'
